import { Button, VerticalBox, HorizontalBox, CheckBox, LineEdit } from "std-widgets.slint";

export component AppWindow inherits Window {
    in property <string> pass: "";

    callback request-generate-password(string, bool, bool, bool);

    title: "password generator";
    
    VerticalBox {
        HorizontalBox {
            Text {
                text: "Length:";
            }
            len := LineEdit {
                text: 16;
                input-type: InputType.number;
            }
        }
        HorizontalBox {
            Text {
                text: "Uppercase:";
            }
            upper := CheckBox {}
        }
        HorizontalBox {
            Text {
                text: "Numbers:";
            }
            num := CheckBox {}
        }
        HorizontalBox {
            Text {
                text: "Symbols:";
            }
            symbols := CheckBox {}
        }

        Text {
            text: "Password: \{root.pass}";
        }

        Button {
            text: "Generate";
            clicked => {
                root.request-generate-password(len.text, upper.checked, num.checked, symbols.checked);
            }
        }
    }
}
