import { Button, VerticalBox, HorizontalBox, CheckBox, LineEdit, Slider } from "std-widgets.slint";

export component AppWindow inherits Window {
    in property <string> pass: "";
    in property <int> len_int: 8;

    callback request-generate-password(string, bool, bool, bool);
    callback slider-toggled(float);

    title: "password generator";
    
    VerticalBox {
        HorizontalBox {
            Text {
                text: "Length: \{len_int}";
            }

            len := Slider {
                minimum: 8;
                maximum: 256;
                changed => {
                    root.slider-toggled(len.value);
                }
            }
        }
        HorizontalBox {
            Text {
                text: "Uppercase:";
            }
            upper := CheckBox {}
        }
        HorizontalBox {
            Text {
                text: "Numbers:";
            }
            num := CheckBox {}
        }
        HorizontalBox {
            Text {
                text: "Symbols:";
            }
            symbols := CheckBox {}
        }

        Text {
            text: "Password: \{root.pass}";
        }

        Button {
            text: "Generate";
            clicked => {
                root.request-generate-password(root.len_int, upper.checked, num.checked, symbols.checked);
            }
        }
    }
}
